list: $/rw/pagebuilder/models/block/columns.yaml
modelClass: Rw\PageBuilder\Models\Block
title: Blocks
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rw/pagebuilder/blocks/update/:id'
