list: $/rw/pagebuilder/models/blocktype/columns.yaml
modelClass: Rw\PageBuilder\Models\BlockType
title: BlockTypes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rw/pagebuilder/blocktypes/update/:id'
